services:

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    env_file:
      - ./.env

  web:
    build: ./
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/app/
      - static_volume:/app/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
    - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: